name: "Update region data"
on:
  schedule:
  - cron: "* * * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Run Script
        run: python3 fetcher/main.py 
